version: '3'
services:
  puppeteer-service:
    build:
      context: ./
    privileged: true
    #platform: linux/arm64
    restart: always
    entrypoint: npm run start-prod
  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - puppeteer-service
    ports:
      - "4444:6000"
    volumes:
      - ./conf.d/balance.conf:/etc/nginx/conf.d/balance.conf
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
